asptraining/Models/Developer.cs
using System.ComponentModel.DataAnnotations;

namespace asptraining.Models
{
    public class Developer
    {
        [Key]
        public int DevID { get; set; }
        [Required(ErrorMessage ="Please provide Firstname")]
        [StringLength(1019,MinimumLength =3, ErrorMessage ="Firstname Must be Between 3 to 1019 characters")]
        public string DevFirstName { get; set; }
        [Required(ErrorMessage = "Please provide Lastname")]
        [StringLength(747, MinimumLength = 3, ErrorMessage = "Lastname Must be Between 3 to 747 characters")]
        public string DevLastName { get; set; }
        [StringLength(747, MinimumLength = 3, ErrorMessage = "Middlename Must be Between 3 to 747 characters")]
        [Required(ErrorMessage = "Please provide Middlename")]
        public string DevMiddleName {get;set;}
        [Required(ErrorMessage = "Please provide Specialty")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Specialty Must be Between 3 to 50 characters")]
        public string Specialty { get; set; }
        public bool IsActive { get; set; }
        [Required(ErrorMessage = "Please provide Hiredate")]
        public DateTime HireDate { get; set; }

    }
}

asptraining/Models/ErrorViewModel.cs
namespace asptraining.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

asptraining/Controllers/DevController.cs
using asptraining.Data;
using asptraining.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace asptraining.Controllers
{
    public class DevController : Controller
    {
        private readonly ApplicationDbContext _db;
        public DevController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            List<Developer> devs = _db.Developer.ToList();

            return View(devs);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Developer devobject)
        {
            if (devobject != null && devobject.DevFirstName.Length < 3)
            {
                ModelState.AddModelError("DevFirstName", "Firstname too short");
            }

            if (devobject != null && devobject.DevMiddleName.Length < 3)
            {
                ModelState.AddModelError("DevMiddleName", "Middlename too short");
            }

            if (devobject != null && devobject.DevLastName.Length < 3)
            {
                ModelState.AddModelError("DevLastName", "Lastname too short");
            }

            if (ModelState.IsValid)
            {
                devobject.IsActive = true;
                _db.Developer.Add(devobject);
                _db.SaveChanges();

            }

            return RedirectToAction("Index");
        }
    }
}

asptraining/Controllers/HomeController.cs
using System.Diagnostics;
using asptraining.Models;
using Microsoft.AspNetCore.Mvc;

namespace asptraining.Controllers
{
    public class HomeController : Controller
    {

        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }


        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Dev()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }



    }
}

asptraining/Views/Dev/Create.cshtml
@model Developer

<div class="container mt-4">
	<div class="row">
		<div class="col-md-8 offset-md-2">
			<div class="card">
				<div class="card-header bg-primary text-white">
					<h2>ADD Developer</h2>
				</div>
				<div class="card-body">
					<form asp-action="Create" method="post">
						@* <div asp-validation-summary="All" class="text-danger"></div> *@
						<div class="form-group mb-3">
							<label asp-for="DevFirstName" class="form-label">First Name:</label>
							<input asp-for="DevFirstName" class="form-control" style="text-transform: uppercase;" oninput="this.value = this.value.toUpperCase()" placeholder="Enter First Name" />
							<span asp-validation-for="DevFirstName" class="text-danger"></span>
						</div>
						<div class="form-group mb-3">
							<label asp-for="DevLastName" class="form-label">Last Name:</label>
							<input asp-for="DevLastName" class="form-control" style="text-transform: uppercase;" oninput="this.value = this.value.toUpperCase()" placeholder="Enter Last Name" />
							<span asp-validation-for="DevLastName" class="text-danger"></span>
						</div>
						<div class="form-group mb-3">
							<label asp-for="DevMiddleName" class="form-label">Middle Name:</label>
							<input asp-for="DevMiddleName" class="form-control" style="text-transform: uppercase;" oninput="this.value = this.value.toUpperCase()" placeholder="Enter Middle Name" />
							<span asp-validation-for="DevMiddleName" class="text-danger"></span>
						</div>
						<div class="form-group mb-3">
							<label asp-for="Specialty" class="form-label">Specialty::</label>
							<input asp-for="Specialty" class="form-control" style="text-transform: uppercase;" oninput="this.value = this.value.toUpperCase()" placeholder="Enter Specialty" />
							<span asp-validation-for="Specialty" class="text-danger"></span>
						</div>
						<div class="form-group mb-3">
							<label asp-for="HireDate" class="form-label">Hiredate:</label>
							<input asp-for="HireDate" type="date" class="form-control" />
							<span asp-validation-for="HireDate" class="text-danger"></span>
						</div>
						<div class="d-flex justify-content-between">
							<button type="submit" class="btn btn-success">Create</button>
							<a asp-controller="Dev" class="btn btn-danger" asp-action="Index">Back to List</a>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>


@section Scripts {
	<partial name="_ValidationScriptsPartial"/>
}

asptraining/Views/Dev/Index.cshtml
@model List<Developer>

<div class="container">
	<div class="row" pt-4>
		<div class="col-6">
			<a class="btn btn-primary" asp-area="" asp-controller="Dev" asp-action="Create">
				<svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-person-plus-fill" viewBox="0 0 16 16">
					<path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6" />
					<path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5" />
				</svg>  ADD Developer
			</a>
		</div>
		<div class="col-6">
			<h2 class="text-end">Developer Entries</h2>
		</div>
	</div>
</div>

<div class="table-responsive">

	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<th>ACTIONS</th>
				<th>FIRST NAME</th>
				<th>MIDDLE INITIAL</th>
				<th>LAST NAME</th>
				<th>SPECIALTY</th>
				@* <th>HIRE DATE</th> *@
			</tr>
			</thead>
		<tbody>
			@foreach (var dev in Model)
			{
				<tr>
					<td>DETAILS || EDIT || DELETE</td>
					<td>@dev.DevFirstName</td>
					<td>
						@(!string.IsNullOrEmpty(dev.DevMiddleName) ? dev.DevMiddleName[0] + "." : "")
					</td>
					<td>@dev.DevLastName</td>
					<td>@dev.Specialty</td>
					@* <td>@dev.HireDate</td> *@
				</tr>
			}
		</tbody>

	</table>


</div>

asptraining/Views/Home/Dev.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="text-center">
    <h1 class="display-4">Developer Details</h1>
    <p>This page provides information about the developer of this project.</p>
 </div>  

asptraining/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">This is my First asp.net project</a>.</p>
</div>

asptraining/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Developers</title>
	<script type="importmap"></script>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/asptraining.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-secondary border-bottom box-shadow mb-3">
			<div class="container-fluid">	
				<a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">
					DEVELOPERS
					<svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-code-slash" viewBox="0 0 16 16">
						<path d="M10.478 1.647a.5.5 0 1 0-.956-.294l-4 13a.5.5 0 0 0 .956.294zM4.854 4.146a.5.5 0 0 1 0 .708L1.707 8l3.147 3.146a.5.5 0 0 1-.708.708l-3.5-3.5a.5.5 0 0 1 0-.708l3.5-3.5a.5.5 0 0 1 .708 0m6.292 0a.5.5 0 0 0 0 .708L14.293 8l-3.147 3.146a.5.5 0 0 0 .708.708l3.5-3.5a.5.5 0 0 0 0-.708l-3.5-3.5a.5.5 0 0 0-.708 0" />
					</svg>
				</a>

				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-white" asp-area="" asp-controller="Dev" asp-action="Index">Dev List</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer bg-dark text-white ">
		<div class="container ">
			&copy; 2025 - Developers List 2025 - <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-white">Privacy</a>
		</div>
	</footer>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>